version: "3.7"

services:
  caddy:
    image: caddy:2-alpine
    restart: "unless-stopped"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - gateway

  gateway:
    image: ghcr.io/paulkaufmanndropily/msi-gateway:latest

  frontend:
    image: ghcr.io/paulkaufmanndropily/msi-frontend:latest

  backend:
    image: ghcr.io/paulkaufmanndropily/msi-backend:latest

volumes:
  caddy_data: ~
  caddy_config: ~
